### ISSUE TITLE
Add a new simulation tool to curated list?

### ISSUE THREAD

**Issue by mfschubert** [joamatab/awesome_photonics#12]
Hi Joaquin, we just open sourced an FMM/RCWA code, [FMMAX](https://github.com/facebookresearch/fmmax) (under MIT license). We'd be thankful if you add it to your list. Cheers!

**Comment by joamatab** [comment]
Thank you Martin! nice work on FMMAX

yes, We can add them to the list!

https://github.com/joamatab/awesome_photonics/pull/14
