### ISSUE TITLE
NLSE and LLE simulations

### ISSUE THREAD

**Issue by DanHickstein** [joamatab/awesome_photonics#8]
In the simulation section, you may consider including some packaged for the nonlinear schrodinger equation (NLSE) to calculate the propagation of pulses along a fiber/waveguide in the presence of dispersion and nonlinearity and the Lugiato Lefever Equation (LLE) to calculate propagation in ring resonators:

NLSE:
Laserfun aims for simplicity: https://github.com/DanHickstein/laserfun
PyNLO is more capable, but unmaintained: https://github.com/pyNLO/PyNLO
cfredrick's fork of PyNLO is essentially it's own thing, and has Chi2 simulation capabilities: https://cdfredrick.github.io/PyNLO/build/html/index.html

LLE:
PyGLLE is nice and simple: https://github.com/omelchert/pyGLLE
PyLLE has more features: https://usnistgov.github.io/pyLLE/

**Comment by joamatab** [comment]
Thank you Dan! We can add them to the list!

**Comment by DanHickstein** [comment]
Awesome! 😎
